# Global settings
import = [
	"alacritty-theme/themes/gruvbox-dark.yaml",
]
working_directory = "/Users/martingwq"

# [shell]
# program = "/opt/homebrew/bin/tmux"
# args = ["new", "-A", "-s", "takina"]

[env]
WHATS_FOR_LUNCH = "🍣"

[window]
decorations = "Full"
opacity = 0.95
startup_mode = "Maximized"
title = "瀧奈"
dynamic_title = true
dynamic_padding = true

[scrolling]
history = 50000
multiplier = 4

[font]
normal = {family = "FiraCode Nerd Font Mono"}
size = 18

